"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import {
  ArrowDownRight, ArrowRight, ArrowUpRight, Ban, BarChart3, Bell, Building2, CalendarDays,
  Check, ChevronDown, CircleDollarSign, CircleX, ClipboardList, Clock3, CreditCard, Download,
  Eye, FileBarChart, FileCheck2, FileText, FolderCheck, Home, LayoutDashboard, Map, MapPin,
  Menu, MoreHorizontal, Pencil, Plus, Search, Settings, SlidersHorizontal, TrendingUp, UserRound,
  Users, X
} from "lucide-react";
import { Brand, StatusBadge } from "@/components/ui";
import { Toast } from "@/components/toast";
import { coordinators, dashboardStats, districtData, documents, registrations, RegistrationRecord, trendData } from "@/data/dashboard";
import { registrationConfig } from "@/data/registration";

const adminLinks=[
  {label:"Dashboard",href:"/admin",icon:LayoutDashboard}, {label:"Registrations",href:"/admin/registrations",icon:ClipboardList},
  {label:"Payments",href:"/admin/payments",icon:CreditCard}, {label:"Reports",href:"/admin/reports",icon:FileBarChart},
  {label:"Districts",href:"/admin/districts",icon:Map}, {label:"Talukas",href:"/admin/talukas",icon:MapPin},
  {label:"Villages",href:"/admin/villages",icon:Home}, {label:"Coordinators",href:"/admin/coordinators",icon:Users},
  {label:"Documents",href:"/admin/documents",icon:FolderCheck}, {label:"Settings",href:"/admin/settings",icon:Settings},
];

function Sidebar({open,onClose}:{open:boolean;onClose:()=>void}){const path=usePathname();return <><aside className={`admin-sidebar ${open?"open":""}`}><div className="admin-logo"><Brand light/><button onClick={onClose}><X/></button></div><div className="admin-workspace"><span>YRA</span><p><b>Admin workspace</b><small>Registration 2026</small></p><ChevronDown/></div><nav>{adminLinks.map(({label,href,icon:Icon})=><Link href={href} key={href} className={path===href?"active":""}><Icon/><span>{label}</span>{label==="Documents"&&<em>4</em>}</Link>)}</nav><div className="admin-side-help"><span><FileCheck2/></span><b>Need a quick report?</b><p>Export registration data from the reports workspace.</p><Link href="/admin/reports">Open reports <ArrowRight/></Link></div><div className="admin-user"><span>AK</span><p><b>Admin User</b><small>Administrator</small></p><MoreHorizontal/></div></aside>{open&&<button className="sidebar-overlay" onClick={onClose} aria-label="Close navigation"/>}</>}

function AdminHeader({title,onMenu}:{title:string;onMenu:()=>void}){return <header className="admin-header"><div><button className="admin-menu" onClick={onMenu}><Menu/></button><div><small>Yuva Rojgar Abhiyan</small><h1>{title}</h1></div></div><div className="admin-header-actions"><div className="admin-search"><Search/><input placeholder="Search anything…"/><kbd>⌘ K</kbd></div><button className="notification"><Bell/><i/></button><div className="profile"><span>AK</span><p><b>Admin</b><small>Super admin</small></p><ChevronDown/></div></div></header>}

function StatCard({label,value,delta,tone,index}:{label:string;value:string;delta:string;tone:string;index:number}){const icons=[ClipboardList,CircleDollarSign,Clock3,CircleX];const Icon=icons[index];return <article className={`stat-card tone-${tone}`}><div><span><Icon/></span><em>{index===3?<ArrowDownRight/>:<ArrowUpRight/>}{delta}</em></div><small>{label}</small><strong>{value}</strong><p>Updated today</p></article>}

function LineChart(){const max=Math.max(...trendData);const points=trendData.map((v,i)=>`${i*(100/(trendData.length-1))},${100-(v/max)*78}`).join(" ");return <div className="line-chart"><div className="chart-grid"><i/><i/><i/><i/></div><svg viewBox="0 0 100 105" preserveAspectRatio="none" role="img" aria-label="Registration trend line chart"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#159a62" stopOpacity=".26"/><stop offset="1" stopColor="#159a62" stopOpacity="0"/></linearGradient></defs><polygon points={`0,105 ${points} 100,105`} fill="url(#area)"/><polyline points={points} fill="none" stroke="#087347" strokeWidth="2" vectorEffect="non-scaling-stroke"/>{trendData.map((v,i)=><circle key={i} cx={i*(100/(trendData.length-1))} cy={100-(v/max)*78} r="1.5" fill="#fff" stroke="#087347" strokeWidth="1"><title>{v} registrations</title></circle>)}</svg><div className="chart-months">{["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep"].map(x=><span key={x}>{x}</span>)}</div></div>}
function DonutChart(){const colors=["#075c3a","#159a62","#59b64b","#e6a235","#c9d8d0"];return <div className="donut-wrap"><div className="donut" style={{background:"conic-gradient(#075c3a 0 28%,#159a62 28% 51%,#59b64b 51% 70%,#e6a235 70% 86%,#c9d8d0 86% 100%)"}}><span><b>12,560</b><small>Total</small></span></div><div className="donut-legend">{districtData.map((d,i)=><div key={d.label}><i style={{background:colors[i]}}/><span>{d.label}</span><b>{d.value.toLocaleString("en-IN")}</b></div>)}</div></div>}
function BarChart({geo="taluka"}:{geo?:string}){const values=geo==="village"?[["Kondhwa",820],["Hadapsar",740],["Kalina",610],["Deolali",540],["Bidkin",460]]:[["Haveli",1250],["Baramati",980],["Indapur",780],["Sinnar",620],["Hingna",540]];return <div className="bar-chart">{values.map(([name,value],i)=><div key={name}><span>{name}</span><i><em style={{width:`${Number(value)/12.5}%`,animationDelay:`${i*80}ms`}}/></i><b>{Number(value).toLocaleString("en-IN")}</b></div>)}</div>}

function Panel({title,subtitle,action,children,className=""}:{title:string;subtitle?:string;action?:React.ReactNode;children:React.ReactNode;className?:string}){return <section className={`admin-panel ${className}`}><div className="panel-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</section>}

function RegistrationsTable({rows=registrations,onView,compact=false}:{rows?:RegistrationRecord[];onView?:(r:RegistrationRecord)=>void;compact?:boolean}){return <div className="responsive-table"><table><thead><tr><th>Registration ID</th><th>Applicant</th><th>Mobile</th><th>Location</th><th>Payment</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} onClick={()=>onView?.(r)}><td><b className="id-cell">{r.id}</b></td><td><div className="applicant-cell"><span>{r.name.split(" ").map(x=>x[0]).join("")}</span><b>{r.name}</b></div></td><td>{r.mobile}</td><td><b>{r.district}</b><small>{r.taluka} · {r.village}</small></td><td><StatusBadge status={r.payment}/></td><td><StatusBadge status={r.status}/></td><td>{r.date}</td><td><button className="table-action" onClick={e=>{e.stopPropagation();onView?.(r)}}><Eye/>View</button></td></tr>)}</tbody></table>{!rows.length&&<EmptyState icon={<Search/>} title="No registrations found" text="Try changing or clearing your current filters."/>}</div>}

function Dashboard(){const [selected,setSelected]=useState<RegistrationRecord|null>(null);return <><div className="stats-grid">{dashboardStats.map((s,i)=><StatCard key={s.label}{...s} index={i}/>)}</div><div className="dashboard-chart-grid"><Panel title="Registration Trends" subtitle="Monthly registrations · 2026" action={<button className="panel-select">This year <ChevronDown/></button>} className="trend-panel"><div className="chart-summary"><strong>12,560</strong><span><TrendingUp/>8.2% vs last period</span></div><LineChart/></Panel><Panel title="District Distribution" subtitle="Top registration locations" action={<button className="icon-button"><MoreHorizontal/></button>}><DonutChart/></Panel></div><div className="dashboard-bottom-grid"><Panel title="Taluka Performance" subtitle="Highest registration volume"><BarChart/></Panel><Panel title="Recent Registrations" subtitle="Latest applicant activity" action={<Link href="/admin/registrations" className="panel-link">View all <ArrowRight/></Link>} className="recent-panel"><RegistrationsTable rows={registrations.slice(0,5)} onView={setSelected} compact/></Panel></div>{selected&&<ApplicantDrawer applicant={selected} onClose={()=>setSelected(null)}/>}</>}

function FilterBar({search,setSearch,status,setStatus}:{search:string;setSearch:(x:string)=>void;status:string;setStatus:(x:string)=>void}){return <div className="filter-bar"><div className="filter-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search ID, name or mobile…"/></div><select><option>All districts</option><option>Pune</option><option>Nagpur</option><option>Nashik</option></select><select><option>All talukas</option><option>Haveli</option><option>Hingna</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>Successful</option><option>Pending</option><option>Failed</option></select><button className="button button-admin"><CalendarDays/>Date range</button><button className="icon-button"><SlidersHorizontal/></button></div>}

function RegistrationsPage(){const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [selected,setSelected]=useState<RegistrationRecord|null>(null);const rows=useMemo(()=>registrations.filter(r=>(!search||`${r.id} ${r.name} ${r.mobile}`.toLowerCase().includes(search.toLowerCase()))&&(!status||r.status===status)),[search,status]);return <><div className="page-title"><div><p>Manage and review every applicant record.</p></div><button className="button button-admin-primary"><Download/>Export CSV</button></div><FilterBar search={search} setSearch={setSearch} status={status} setStatus={setStatus}/><Panel title="All Registrations" subtitle={`${rows.length} records in the current view`} action={<div className="pagination-text">Showing 1–{rows.length} of {rows.length}</div>}><RegistrationsTable rows={rows} onView={setSelected}/></Panel>{selected&&<ApplicantDrawer applicant={selected} onClose={()=>setSelected(null)}/>}</>}

function ApplicantDrawer({applicant,onClose}:{applicant:RegistrationRecord;onClose:()=>void}){return <><button className="drawer-overlay" onClick={onClose}/><aside className="applicant-drawer"><div className="drawer-head"><div className="drawer-person"><span>{applicant.name.split(" ").map(x=>x[0]).join("")}</span><p><b>{applicant.name}</b><small>{applicant.id}</small></p></div><button onClick={onClose}><X/></button></div><div className="drawer-status"><StatusBadge status={applicant.status}/><StatusBadge status={applicant.payment}/><span>Applied {applicant.date}</span></div><div className="drawer-body">{[
  {t:"Personal Details",i:UserRound,d:[["Full name",applicant.name],["Mobile",applicant.mobile],["Age","24 years"],["Applicant photo","Uploaded"]]},
  {t:"Address",i:MapPin,d:[["District",applicant.district],["Taluka",applicant.taluka],["Village",applicant.village]]},
  {t:"Education & Employment",i:Building2,d:[["Education",applicant.education],["Employment",applicant.employment],["Job preference","Private Sector"]]},
  {t:"Loan Requirement",i:CircleDollarSign,d:[["Requirement",applicant.loan],["Purpose",applicant.loan==="No"?"Not applicable":"Small business setup"]]},
  {t:"Documents",i:FolderCheck,d:[["Applicant photo","Verified"],["Education document","Pending review"]]},
  {t:"Payment",i:CreditCard,d:[["Amount","₹100.00"],["Method","UPI"],["Transaction ID","TXN2608180001"],["Status",applicant.payment]]},
].map(({t,i:Icon,d})=><section key={t}><h3><Icon/>{t}</h3><div>{d.map(([a,b])=><p key={a}><small>{a}</small><b>{b}</b></p>)}</div></section>)}</div><div className="drawer-actions"><button className="button button-admin"><Pencil/>Edit record</button><button className="button button-admin-primary">Update status <ChevronDown/></button></div></aside></>}

function PaymentsPage(){const paid=registrations.filter(r=>r.payment==="Paid");return <><div className="admin-summary-grid"><div><span><CircleDollarSign/></span><p><small>Total collected</small><b>₹10,24,500</b><em>10,245 payments</em></p></div><div><span><Clock3/></span><p><small>Pending amount</small><b>₹1,48,200</b><em>1,482 payments</em></p></div><div><span><CircleX/></span><p><small>Failed amount</small><b>₹83,300</b><em>833 payments</em></p></div></div><div className="filter-bar"><div className="filter-search"><Search/><input placeholder="Search transaction or applicant…"/></div><select><option>All methods</option><option>UPI</option><option>Card</option><option>Net Banking</option></select><select><option>All statuses</option><option>Paid</option><option>Pending</option><option>Failed</option></select><button className="button button-admin"><CalendarDays/>Date range</button></div><Panel title="Payment Transactions" subtitle="Mock transaction activity"><div className="responsive-table"><table><thead><tr><th>Registration ID</th><th>Applicant</th><th>Amount</th><th>Payment Method</th><th>Transaction ID</th><th>Date</th><th>Status</th></tr></thead><tbody>{registrations.map((r,i)=><tr key={r.id}><td><b className="id-cell">{r.id}</b></td><td>{r.name}</td><td><b>₹100.00</b></td><td>{i%3===0?"Google Pay":i%3===1?"UPI":"Debit Card"}</td><td>TXN2608{String(180001+i)}</td><td>{r.date}</td><td><StatusBadge status={r.payment}/></td></tr>)}</tbody></table></div></Panel></>}

function ReportsPage(){const [toast,setToast]=useState("");const reports=[{t:"Registration Report",x:"Applicant records and registration status.",i:ClipboardList},{t:"Payment Report",x:"Transactions, payment method and status.",i:CreditCard},{t:"District Report",x:"Registration summary by district.",i:Map},{t:"Taluka Report",x:"Taluka-level volume and completion.",i:MapPin},{t:"Village Report",x:"Local registration distribution.",i:Home}];function csv(title:string){const content="Registration ID,Applicant,Status\n"+registrations.map(r=>`${r.id},${r.name},${r.status}`).join("\n");const url=URL.createObjectURL(new Blob([content],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download=`${title.toLowerCase().replaceAll(" ","-")}.csv`;a.click();URL.revokeObjectURL(url);setToast(`${title} CSV exported.`)}return <><div className="report-banner"><div><span><FileBarChart/></span><div><small>REPORTING WORKSPACE</small><h2>Turn registration activity into clear exports.</h2><p>Choose a report, date range and output format.</p></div></div><div className="report-banner-stats"><p><small>Available reports</small><b>05</b></p><p><small>Last export</small><b>Today, 10:24</b></p></div></div><div className="report-grid">{reports.map(({t,x,i:Icon})=><article key={t}><span><Icon/></span><h2>{t}</h2><p>{x}</p><div className="report-options"><label><small>Date range</small><select><option>This month</option><option>This quarter</option><option>This year</option></select></label><label><small>Status</small><select><option>All statuses</option><option>Successful</option><option>Pending</option></select></label></div><div><button className="button button-admin-primary" onClick={()=>csv(t)}><Download/>Export CSV</button><button className="button button-admin" onClick={()=>window.print()}><FileText/>Export PDF</button></div></article>)}</div>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</>}

const geoMap={districts:{singular:"District",records:[["Pune","2,560","81%","+12%"],["Mumbai Suburban","2,145","84%","+8%"],["Nagpur","1,890","79%","+15%"],["Nashik","1,450","80%","+5%"],["Aurangabad","1,250","76%","+9%"]]},talukas:{singular:"Taluka",records:[["Haveli","1,250","84%","+14%"],["Baramati","980","80%","+9%"],["Indapur","780","77%","+11%"],["Sinnar","620","81%","+6%"],["Hingna","540","79%","+12%"]]},villages:{singular:"Village",records:[["Kondhwa","820","86%","+18%"],["Hadapsar","740","82%","+10%"],["Kalina","610","79%","+8%"],["Deolali","540","80%","+7%"],["Bidkin","460","75%","+13%"]]}};
function GeoPage({section}:{section:"districts"|"talukas"|"villages"}){const cfg=geoMap[section];return <><div className="geo-stats"><div><small>Total {section}</small><b>{section==="districts"?"36":section==="talukas"?"358":"4,216"}</b><span>In local configuration</span></div><div><small>Top {cfg.singular}</small><b>{cfg.records[0][0]}</b><span>{cfg.records[0][1]} registrations</span></div><div><small>Average paid rate</small><b>81.2%</b><span>Across listed locations</span></div></div><div className="geo-grid"><Panel title={`${cfg.singular} Performance`} subtitle="Registration volume by location" action={<button className="panel-select">This year <ChevronDown/></button>}><BarChart geo={section}/></Panel><Panel title="Payment Completion" subtitle={`Paid registration rate by ${cfg.singular.toLowerCase()}`}><div className="completion-list">{cfg.records.map((r,i)=><div key={r[0]}><span>{i+1}</span><p><b>{r[0]}</b><small>{r[1]} registrations</small></p><em>{r[2]}</em></div>)}</div></Panel></div><Panel title={`All ${cfg.singular}s`} subtitle="Location-level registration activity" action={<button className="button button-admin"><Download/>Export</button>}><div className="responsive-table"><table><thead><tr><th>{cfg.singular}</th><th>Registrations</th><th>Paid Rate</th><th>Trend</th><th>Coordinator</th><th>Action</th></tr></thead><tbody>{cfg.records.map((r,i)=><tr key={r[0]}><td><div className="location-cell"><span><MapPin/></span><b>{r[0]}</b></div></td><td><b>{r[1]}</b></td><td>{r[2]}</td><td><em className="positive"><ArrowUpRight/>{r[3]}</em></td><td>{coordinators[i%coordinators.length].name}</td><td><button className="table-action"><Eye/>View</button></td></tr>)}</tbody></table></div></Panel></>}

function CoordinatorsPage(){const [toast,setToast]=useState("");return <><div className="page-title"><p>Assign and manage local programme coordinators.</p><button onClick={()=>setToast("Coordinator form opened in this demo.")} className="button button-admin-primary"><Plus/>Add Coordinator</button></div><div className="filter-bar"><div className="filter-search"><Search/><input placeholder="Search coordinators…"/></div><select><option>All districts</option><option>Pune</option><option>Nagpur</option></select><select><option>All statuses</option><option>Active</option><option>Inactive</option></select></div><Panel title="Coordinator Directory" subtitle={`${coordinators.length} local mock records`}><div className="coordinator-grid">{coordinators.map(c=><article key={c.name}><div className="coordinator-top"><span>{c.name.split(" ").map(x=>x[0]).join("")}</span><StatusBadge status={c.status}/></div><h3>{c.name}</h3><p>{c.mobile}</p><div><small>District<b>{c.district}</b></small><small>Taluka<b>{c.taluka}</b></small></div><footer><button onClick={()=>setToast(`Viewing ${c.name}.`)}><Eye/>View</button><button onClick={()=>setToast(`Editing ${c.name}.`)}><Pencil/>Edit</button><button onClick={()=>setToast(`${c.name} status action recorded.`)}><Ban/>Deactivate</button></footer></article>)}</div></Panel>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</>}

function DocumentsPage(){const [filter,setFilter]=useState("All");const shown=documents.filter(d=>filter==="All"||d.status===filter);return <><div className="document-tabs">{["All","Pending","Verified","Rejected"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}<span>{x==="All"?documents.length:documents.filter(d=>d.status===x).length}</span></button>)}</div><Panel title="Applicant Documents" subtitle="Review upload and verification status" action={<button className="button button-admin"><Download/>Export list</button>}><div className="responsive-table"><table><thead><tr><th>Applicant</th><th>Document</th><th>Upload Date</th><th>Verification Status</th><th>Action</th></tr></thead><tbody>{shown.map((d,i)=><tr key={`${d.applicant}${d.document}`}><td><div className="applicant-cell"><span>{d.applicant.split(" ").map(x=>x[0]).join("")}</span><b>{d.applicant}</b></div></td><td><div className="document-cell"><FileText/><p><b>{d.document}</b><small>JPG · {1.2+i/10} MB</small></p></div></td><td>{d.date}</td><td><StatusBadge status={d.status}/></td><td><button className="table-action"><Eye/>Review</button></td></tr>)}</tbody></table>{!shown.length&&<EmptyState icon={<FolderCheck/>} title="No documents here" text="There are no documents with this status."/>}</div></Panel></>}

function Toggle({on,set}:{on:boolean;set:(x:boolean)=>void}){return <button onClick={()=>set(!on)} className={`toggle ${on?"on":""}`} role="switch" aria-checked={on}><i/></button>}
function SettingsPage(){const [fee,setFee]=useState("100");const [email,setEmail]=useState(true);const [sms,setSms]=useState(true);const [whatsapp,setWhatsapp]=useState(false);const [toast,setToast]=useState("");return <><div className="settings-layout"><nav><a href="#registration" className="active"><CircleDollarSign/>Registration</a><a href="#notifications"><Bell/>Notifications</a><a href="#general"><Settings/>General</a></nav><div><Panel title="Registration Settings" subtitle="Configure fee and ID rules" className="settings-panel"><div id="registration" className="settings-fields"><label><span>Registration Fee<small>Displayed at review and payment.</small></span><div className="setting-input"><i>₹</i><input value={fee} onChange={e=>setFee(e.target.value.replace(/\D/g,""))}/></div></label><label><span>Registration ID Format<small>Generated after successful payment.</small></span><input value="YRA-YYYY-XXXXX" readOnly/></label><label><span>Registration Year<small>Used in the generated ID.</small></span><select defaultValue="2026"><option>2026</option><option>2027</option></select></label></div></Panel><Panel title="Notification Preferences" subtitle="Choose demonstration communication channels" className="settings-panel"><div id="notifications" className="notification-settings"><div><span><b>Email notifications</b><small>Registration and payment confirmations</small></span><Toggle on={email} set={setEmail}/></div><div><span><b>SMS notifications</b><small>Status updates to applicant mobile</small></span><Toggle on={sms} set={setSms}/></div><div><span><b>WhatsApp notifications</b><small>Confirmation to provided WhatsApp number</small></span><Toggle on={whatsapp} set={setWhatsapp}/></div></div></Panel><Panel title="General Settings" subtitle="Programme display information" className="settings-panel"><div id="general" className="settings-fields"><label><span>Programme Name<small>Shown throughout the platform.</small></span><input defaultValue="Yuva Rojgar Abhiyan"/></label><label><span>Tagline<small>Primary public-facing message.</small></span><input defaultValue="Empowering Youth, Building Future"/></label></div></Panel><div className="settings-actions"><button className="button button-admin" onClick={()=>location.reload()}>Discard changes</button><button className="button button-admin-primary" onClick={()=>setToast("Settings saved locally for this session.")}><Check/>Save settings</button></div></div></div>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</>}

function EmptyState({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty-state"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>}
function AdminSkeleton(){return <div className="admin-skeleton" aria-label="Loading dashboard"><div className="skeleton-stats">{[1,2,3,4].map(x=><i key={x}/>)}</div><div className="skeleton-panels"><i/><i/></div><div className="skeleton-table"><b/><i/><i/><i/><i/></div></div>}

const titles:Record<string,string>={dashboard:"Dashboard",registrations:"Registrations",payments:"Payments",reports:"Reports",districts:"District Analytics",talukas:"Taluka Analytics",villages:"Village Analytics",coordinators:"Coordinators",documents:"Documents",settings:"Settings"};
export default function AdminApp({section="dashboard"}:{section?:string}){const [menu,setMenu]=useState(false);const [loading,setLoading]=useState(true);const title=titles[section]||"Dashboard";useEffect(()=>{const timer=setTimeout(()=>setLoading(false),450);return()=>clearTimeout(timer)},[section]);return <main className="admin-app"><Sidebar open={menu} onClose={()=>setMenu(false)}/><div className="admin-main"><AdminHeader title={title} onMenu={()=>setMenu(true)}/><div className="admin-content">{loading?<AdminSkeleton/>:<>{section==="dashboard"&&<Dashboard/>}{section==="registrations"&&<RegistrationsPage/>}{section==="payments"&&<PaymentsPage/>}{section==="reports"&&<ReportsPage/>}{(section==="districts"||section==="talukas"||section==="villages")&&<GeoPage section={section}/>} {section==="coordinators"&&<CoordinatorsPage/>}{section==="documents"&&<DocumentsPage/>}{section==="settings"&&<SettingsPage/>}</>}</div></div></main>}
