"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ChangeEvent, FormEvent, ReactNode, useEffect, useState } from "react";
import {
  ArrowLeft, ArrowRight, BadgeCheck, Banknote, Building2, Check, CheckCircle2, ChevronRight,
  CircleHelp, CreditCard, Download, FileCheck2, GraduationCap, Home, IdCard, ImagePlus,
  Landmark, LockKeyhole, MapPin, Pencil, Phone, QrCode, Rocket, ShieldCheck, Smartphone,
  UploadCloud, UserRound, WalletCards, X
} from "lucide-react";
import { Brand, StatusBadge } from "@/components/ui";
import { Toast } from "@/components/toast";
import { districts } from "@/data/districts";
import { talukas } from "@/data/talukas";
import { villages } from "@/data/villages";
import { educationOptions, employmentOptions, jobPreferences, registrationConfig, registrationSteps, selfEmploymentPreferences } from "@/data/registration";

type FormData = {
  fullName:string; mobile:string; whatsapp:string; age:string; photo:string; district:string; taluka:string; village:string;
  education:string; employment:string; jobPreference:string; selfEmployment:string; businessInterest:string;
  loanRequired:"Yes"|"No"|""; loanAmount:string; loanPurpose:string;
};

const initialData: FormData = { fullName:"",mobile:"",whatsapp:"",age:"",photo:"",district:"",taluka:"",village:"",education:"",employment:"",jobPreference:"",selfEmployment:"",businessInterest:"",loanRequired:"",loanAmount:"",loanPurpose:"" };
const pathToStep: Record<string,number> = {"personal-details":1,"address-details":2,"education-employment":3,"loan-requirement":4,"review":5,"payment":6};

function Field({label,required,error,children,hint}:{label:string;required?:boolean;error?:string;children:ReactNode;hint?:string}){
  return <div className={`field ${error?"field-error":""}`}><label>{label}{required&&<em>*</em>}</label>{children}{hint&&!error&&<small>{hint}</small>}{error&&<small className="error-text">{error}</small>}</div>;
}

function Stepper({current}:{current:number}){
  return <div className="stepper-wrap"><div className="registration-stepper">{registrationSteps.map(s=><div className={`stepper-item ${s.id===current?"active":s.id<current?"done":""}`} key={s.id}><span>{s.id<current?<Check size={14}/>:String(s.id).padStart(2,"0")}</span><p><small>STEP {String(s.id).padStart(2,"0")}</small><b>{s.label}</b></p><i/></div>)}</div></div>;
}

function AppChrome({current}:{current?:number}){
  return <><header className="registration-header"><div className="container"><Brand/><div className="registration-header-meta"><span><ShieldCheck/> Guided registration</span><Link href="/faq"><CircleHelp/>Help</Link><Link href="/" aria-label="Close registration"><X/></Link></div></div></header>{current&&<div className="sticky-stepper"><div className="container"><Stepper current={current}/></div></div>}</>;
}

export default function RegistrationApp({stepSlug}:{stepSlug?:string}){
  const router=useRouter(); const current=stepSlug?pathToStep[stepSlug]||0:0;
  const [data,setData]=useState<FormData>(initialData); const [hydrated,setHydrated]=useState(false); const [attempted,setAttempted]=useState(false); const [toast,setToast]=useState("");
  useEffect(()=>{try{const saved=localStorage.getItem("yra-registration");if(saved)setData({...initialData,...JSON.parse(saved)})}catch{}setHydrated(true)},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem("yra-registration",JSON.stringify(data))},[data,hydrated]);
  const update=(key:keyof FormData,value:string)=>setData(d=>({...d,[key]:value}));
  const go=(path:string)=>{setAttempted(false);router.push(path)};

  if(stepSlug==="success") return <SuccessPage data={data}/>;
  if(!current) return <RegistrationWelcome/>;

  const personalErrors={fullName:data.fullName.trim().length<3?"Enter your full name.":"",mobile:!/^\d{10}$/.test(data.mobile)?"Enter a valid 10-digit mobile number.":"",age:!data.age||+data.age<18||+data.age>99?"Enter an age between 18 and 99.":"",photo:!data.photo?"Please choose an applicant photo.":""};
  const addressErrors={district:!data.district?"Select a district.":"",taluka:!data.taluka?"Select a taluka.":"",village:!data.village?"Select a village.":""};
  const educationErrors={education:!data.education?"Select your education.":"",employment:!data.employment?"Select your employment status.":"",jobPreference:!data.jobPreference?"Select a job preference.":"",selfEmployment:!data.selfEmployment?"Select a self-employment preference.":"",businessInterest:data.businessInterest.trim().length<2?"Tell us your business interest or enter ‘Not sure’.":""};
  const loanErrors={loanRequired:!data.loanRequired?"Please choose Yes or No.":"",loanAmount:data.loanRequired==="Yes"&&!data.loanAmount?"Enter the required amount.":"",loanPurpose:data.loanRequired==="Yes"&&data.loanPurpose.trim().length<3?"Describe the loan or business purpose.":""};
  const errors=current===1?personalErrors:current===2?addressErrors:current===3?educationErrors:loanErrors;
  function next(e:FormEvent,nextPath:string){e.preventDefault();setAttempted(true);if(Object.values(errors).some(Boolean))return;setToast("Progress saved on this device.");setTimeout(()=>go(nextPath),350)}

  return <main className="registration-app"><AppChrome current={current}/><div className="registration-bg"><div className="container registration-layout"><aside className="registration-aside"><span>APPLICATION</span><h2>Your future starts with one clear step.</h2><p>Complete each section at your pace. Your information is saved locally on this device.</p><div><ShieldCheck/><p><b>Review before payment</b><small>You can edit every section before continuing.</small></p></div><div><LockKeyhole/><p><b>Local demonstration</b><small>No database or remote storage is used.</small></p></div></aside>
    <section className="form-card">{current===1&&<form onSubmit={e=>next(e,"/register/address-details")}><FormHead icon={<UserRound/>} step="01" title="Personal Details" text="Let’s begin with a few basic details."/>
      <div className="form-grid"><Field label="Full Name" required error={attempted?personalErrors.fullName:""}><input value={data.fullName} onChange={e=>update("fullName",e.target.value)} placeholder="Enter your full name" autoComplete="name"/></Field><Field label="Mobile Number" required error={attempted?personalErrors.mobile:""}><div className="input-prefix"><span>+91</span><input value={data.mobile} onChange={e=>update("mobile",e.target.value.replace(/\D/g,"").slice(0,10))} placeholder="10-digit mobile number" inputMode="numeric" autoComplete="tel"/></div></Field><Field label="WhatsApp Number" hint="Leave blank if same as mobile"><div className="input-prefix"><span>+91</span><input value={data.whatsapp} onChange={e=>update("whatsapp",e.target.value.replace(/\D/g,"").slice(0,10))} placeholder="WhatsApp number" inputMode="numeric"/></div></Field><Field label="Age" required error={attempted?personalErrors.age:""}><input type="number" min="18" max="99" value={data.age} onChange={e=>update("age",e.target.value)} placeholder="Enter your age"/></Field><div className="full"><Field label="Applicant Photo" required error={attempted?personalErrors.photo:""} hint="JPG or PNG · maximum 5 MB"><label className="upload-field"><input type="file" accept="image/png,image/jpeg" onChange={(e:ChangeEvent<HTMLInputElement>)=>update("photo",e.target.files?.[0]?.name||"")}/><span><UploadCloud/></span><p><b>{data.photo||"Choose a recent photo"}</b><small>Click to browse from this device</small></p><em>Browse</em></label></Field></div></div><FormActions back="/" next="Continue to Address"/></form>}

      {current===2&&<form onSubmit={e=>next(e,"/register/education-employment")}><FormHead icon={<MapPin/>} step="02" title="Address Details" text="Select your location to keep your application accurate."/><div className="form-grid single-column"><Field label="District" required error={attempted?addressErrors.district:""}><select value={data.district} onChange={e=>{update("district",e.target.value);update("taluka","");update("village","")}}><option value="">Select district</option>{districts.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Taluka" required error={attempted?addressErrors.taluka:""}><select value={data.taluka} disabled={!data.district} onChange={e=>{update("taluka",e.target.value);update("village","")}}><option value="">Select taluka</option>{(talukas[data.district]||[]).map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Village / Locality" required error={attempted?addressErrors.village:""}><select value={data.village} disabled={!data.taluka} onChange={e=>update("village",e.target.value)}><option value="">Select village</option>{(villages[data.taluka]||[]).map(x=><option key={x}>{x}</option>)}</select></Field></div><div className="cascade-note"><MapPin/><p><b>Location selection is connected</b><small>Available talukas and villages change based on your previous choice.</small></p></div><FormActions back="/register/personal-details" next="Continue to Education"/></form>}

      {current===3&&<form onSubmit={e=>next(e,"/register/loan-requirement")}><FormHead icon={<GraduationCap/>} step="03" title="Education & Employment" text="Tell us about your current position and direction."/><div className="form-grid"><Field label="Highest Education" required error={attempted?educationErrors.education:""}><select value={data.education} onChange={e=>update("education",e.target.value)}><option value="">Select education</option>{educationOptions.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Employment Status" required error={attempted?educationErrors.employment:""}><select value={data.employment} onChange={e=>update("employment",e.target.value)}><option value="">Select status</option>{employmentOptions.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Job Preference" required error={attempted?educationErrors.jobPreference:""}><select value={data.jobPreference} onChange={e=>update("jobPreference",e.target.value)}><option value="">Select preference</option>{jobPreferences.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Self-Employment Preference" required error={attempted?educationErrors.selfEmployment:""}><select value={data.selfEmployment} onChange={e=>update("selfEmployment",e.target.value)}><option value="">Select preference</option>{selfEmploymentPreferences.map(x=><option key={x}>{x}</option>)}</select></Field><div className="full"><Field label="Business Interest" required error={attempted?educationErrors.businessInterest:""} hint="You may enter ‘Not sure’ if you are still exploring"><input value={data.businessInterest} onChange={e=>update("businessInterest",e.target.value)} placeholder="e.g. Retail, food services, digital work"/></Field></div></div><FormActions back="/register/address-details" next="Continue to Loan"/></form>}

      {current===4&&<form onSubmit={e=>next(e,"/register/review")}><FormHead icon={<Landmark/>} step="04" title="Loan Requirement" text="Is a loan relevant to the business path you want to explore?"/><Field label="Loan Required?" required error={attempted?loanErrors.loanRequired:""}><div className="choice-grid"><button type="button" className={data.loanRequired==="Yes"?"selected":""} onClick={()=>update("loanRequired","Yes")}><span>{data.loanRequired==="Yes"?<Check/>:<CircleHelp/>}</span><b>Yes, record a requirement</b><small>I have an estimated amount or purpose.</small></button><button type="button" className={data.loanRequired==="No"?"selected":""} onClick={()=>{update("loanRequired","No");update("loanAmount","");update("loanPurpose","")}}><span>{data.loanRequired==="No"?<Check/>:<X/>}</span><b>No, not right now</b><small>I want to continue without this.</small></button></div></Field>{data.loanRequired==="Yes"&&<div className="conditional-fields"><Field label="Required Loan Amount" required error={attempted?loanErrors.loanAmount:""}><div className="input-prefix rupee"><span>₹</span><input value={data.loanAmount} onChange={e=>update("loanAmount",e.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="Enter estimated amount"/></div></Field><Field label="Purpose of Loan / Business" required error={attempted?loanErrors.loanPurpose:""}><textarea rows={4} value={data.loanPurpose} onChange={e=>update("loanPurpose",e.target.value)} placeholder="Briefly describe the intended purpose"/></Field></div>}<div className="form-disclaimer"><CircleHelp/><p>Recording a requirement does not guarantee loan approval. Confirmed programme policy can be added here when available.</p></div><FormActions back="/register/education-employment" next="Review Application"/></form>}

      {current===5&&<ReviewStep data={data} onContinue={()=>go("/register/payment")}/>} {current===6&&<PaymentStep data={data} onSuccess={()=>go("/register/success")}/>} 
    </section></div></div>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</main>;
}

function FormHead({icon,step,title,text}:{icon:ReactNode;step:string;title:string;text:string}){return <div className="form-head"><span>{icon}</span><div><small>STEP {step} OF 06</small><h1>{title}</h1><p>{text}</p></div></div>}
function FormActions({back,next}:{back:string;next:string}){return <div className="form-actions"><Link href={back} className="button button-muted"><ArrowLeft size={16}/>Back</Link><button className="button button-primary" type="submit">{next}<ArrowRight size={16}/></button></div>}

function RegistrationWelcome(){return <main className="registration-welcome"><AppChrome/><div className="welcome-visual"><Image src="/images/hero/yra-youth.jpg" alt="Young Indian students and professionals" fill priority sizes="100vw"/><div className="welcome-shade"/><div className="container"><div className="welcome-card"><span className="welcome-icon"><Rocket/></span><small>ONLINE REGISTRATION · 2026</small><h1>Let’s build your<br/>profile, together.</h1><p>Complete six clear steps and receive your unique registration ID after the ₹100 payment stage.</p><div className="welcome-meta"><div><span>01</span><p><b>About 6–8 minutes</b><small>Simple guided fields</small></p></div><div><span>₹</span><p><b>₹100 registration fee</b><small>Shown before payment</small></p></div></div><Link href="/register/personal-details" className="button button-orange">Start Registration <ArrowRight/></Link><Link href="/how-it-works" className="welcome-link">How the process works <ChevronRight/></Link></div></div></div></main>}

function ReviewSection({title,icon,edit,items}:{title:string;icon:ReactNode;edit:string;items:[string,string][]}){return <div className="review-section"><div className="review-title"><span>{icon}</span><h2>{title}</h2><Link href={edit}><Pencil/>Edit</Link></div><div className="review-items">{items.map(([a,b])=><div key={a}><small>{a}</small><b>{b||"—"}</b></div>)}</div></div>}
function ReviewStep({data,onContinue}:{data:FormData;onContinue:()=>void}){return <div><FormHead icon={<FileCheck2/>} step="05" title="Review Your Application" text="Check every detail before moving to the payment step."/><div className="review-list"><ReviewSection title="Personal Information" icon={<UserRound/>} edit="/register/personal-details" items={[["Full Name",data.fullName],["Mobile",`+91 ${data.mobile}`],["WhatsApp",data.whatsapp?`+91 ${data.whatsapp}`:"Same as mobile"],["Age",data.age]]}/><ReviewSection title="Address" icon={<MapPin/>} edit="/register/address-details" items={[["District",data.district],["Taluka",data.taluka],["Village",data.village]]}/><ReviewSection title="Education & Employment" icon={<GraduationCap/>} edit="/register/education-employment" items={[["Education",data.education],["Employment",data.employment],["Job Preference",data.jobPreference],["Self-Employment",data.selfEmployment],["Business Interest",data.businessInterest]]}/><ReviewSection title="Loan Requirement" icon={<Landmark/>} edit="/register/loan-requirement" items={[["Loan Required",data.loanRequired||"No"],["Estimated Amount",data.loanAmount?`₹${Number(data.loanAmount).toLocaleString("en-IN")}`:"Not applicable"],["Purpose",data.loanPurpose||"Not applicable"]]}/><ReviewSection title="Documents" icon={<ImagePlus/>} edit="/register/personal-details" items={[["Applicant Photo",data.photo||"Not selected"]]}/></div><div className="review-confirm"><CheckCircle2/><p><b>Ready for payment</b><small>By continuing, you confirm that you have reviewed the information shown above.</small></p></div><div className="form-actions"><Link href="/register/loan-requirement" className="button button-muted"><ArrowLeft/>Back</Link><button className="button button-primary" onClick={onContinue}>Continue to Payment <ArrowRight/></button></div></div>}

const paymentMethods=[{id:"upi",label:"UPI",sub:"Use any UPI app",icon:QrCode},{id:"gpay",label:"Google Pay",sub:"Continue via UPI",icon:Smartphone},{id:"phonepe",label:"PhonePe",sub:"Continue via UPI",icon:Phone},{id:"paytm",label:"Paytm",sub:"Wallet or UPI",icon:WalletCards},{id:"card",label:"Debit / Credit Card",sub:"Visa, Mastercard, RuPay",icon:CreditCard},{id:"bank",label:"Net Banking",sub:"Choose your bank",icon:Building2}];
function PaymentStep({data,onSuccess}:{data:FormData;onSuccess:()=>void}){const [method,setMethod]=useState("upi");const [loading,setLoading]=useState(false);function pay(){setLoading(true);setTimeout(()=>{localStorage.setItem("yra-registration-id","YRA-2026-00001");onSuccess()},1500)}return <div><FormHead icon={<CreditCard/>} step="06" title="Complete Payment" text="Choose a payment method and review the fee before registering."/><div className="payment-layout"><div className="payment-summary"><div className="payment-person"><span>{data.fullName?.charAt(0)||"Y"}</span><p><b>{data.fullName||"YRA Applicant"}</b><small>{data.mobile?`+91 ${data.mobile}`:"Applicant details"}</small></p></div><h3>Registration summary</h3>{[["Location",[data.village,data.taluka].filter(Boolean).join(", ")||"—"],["Education",data.education||"—"],["Employment",data.employment||"—"],["Loan Requirement",data.loanRequired||"No"]].map(([a,b])=><div className="summary-row" key={a}><span>{a}</span><b>{b}</b></div>)}<div className="fee-total"><span>Registration Fee</span><strong>₹{registrationConfig.fee}.00</strong></div></div><div className="payment-methods"><h3>Choose payment method</h3><p>Select one option to continue.</p>{paymentMethods.map(({id,label,sub,icon:Icon})=><button className={method===id?"selected":""} key={id} onClick={()=>setMethod(id)}><i><Icon/></i><span><b>{label}</b><small>{sub}</small></span><em>{method===id&&<Check/>}</em></button>)}</div></div><div className="payment-action"><div><LockKeyhole/><p><b>Demonstration payment</b><small>No actual charge will be made in this generated platform.</small></p></div><button onClick={pay} className="button button-orange" disabled={loading}>{loading?<><span className="spinner"/>Processing payment…</>:<>Pay ₹100 & Register <ArrowRight/></>}</button></div><div className="form-actions payment-back"><Link href="/register/review" className="button button-muted"><ArrowLeft/>Back to review</Link></div></div>}

function SuccessPage({data}:{data:FormData}){function download(){const content=`YUVA ROJGAR ABHIYAN\nRegistration ID: YRA-2026-00001\nApplicant: ${data.fullName||"Rohit Kumar"}\nPayment: ₹100\nStatus: Successful`;const url=URL.createObjectURL(new Blob([content],{type:"text/plain"}));const a=document.createElement("a");a.href=url;a.download="YRA-2026-00001.txt";a.click();URL.revokeObjectURL(url)}return <main className="success-page"><AppChrome/><div className="success-orb one"/><div className="success-orb two"/><div className="container success-wrap"><div className="success-card"><div className="success-check"><Check/></div><span className="success-kicker">PAYMENT VERIFIED</span><h1>Registration<br/>Successful!</h1><p>Your registration has been completed successfully.</p><div className="success-id"><small>YOUR REGISTRATION ID</small><strong>YRA-2026-00001</strong><button onClick={()=>navigator.clipboard?.writeText("YRA-2026-00001")} aria-label="Copy registration ID"><IdCard/></button></div><div className="success-details"><div><small>Payment</small><b>₹100.00</b></div><div><small>Status</small><StatusBadge status="Successful"/></div></div><div className="success-actions"><button className="button button-outline" onClick={download}><Download/>Download Details</button><Link href="/registration-status" className="button button-primary">Check Registration Status <ArrowRight/></Link></div><Link href="/" className="go-home"><Home/>Go To Home</Link></div><div className="success-side"><span><BadgeCheck/></span><h2>Keep this ID safe.</h2><p>You’ll need it whenever you check the status of your registration.</p><div><ShieldCheck/><p><b>Confirmation ready</b><small>A printable confirmation is available.</small></p></div><Link href="/confirmation">View confirmation <ChevronRight/></Link></div></div></main>}
